controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


simple_velocity_controller:
  ros__parameters:
    joints:
      - joint_roda_1
      - joint_roda_2
      - joint_roda_3
      - joint_roda_4


